# Generated by Django 5.0.7 on 2024-11-03 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fanaDashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FanaCallRequest",
        ),
    ]
