# Generated by Django 5.0.7 on 2024-07-26 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fanaCallSetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanacallrequest",
            name="handled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fanacallrequest",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
