# Generated by Django 5.0.7 on 2024-07-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fanaCallSetup", "0002_fanacallrequest_handled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fanacallrequest",
            name="handled",
        ),
        migrations.RemoveField(
            model_name="fanacallrequest",
            name="request_type",
        ),
        migrations.AddField(
            model_name="fanacallrequest",
            name="bring_bill_state",
            field=models.CharField(
                choices=[
                    ("pressed", "Pressed"),
                    ("not_pressed", "Not Pressed"),
                    ("in_progress", "In Progress"),
                ],
                default="not_pressed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fanacallrequest",
            name="bring_water_state",
            field=models.CharField(
                choices=[
                    ("pressed", "Pressed"),
                    ("not_pressed", "Not Pressed"),
                    ("in_progress", "In Progress"),
                ],
                default="not_pressed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fanacallrequest",
            name="call_waiter_state",
            field=models.CharField(
                choices=[
                    ("pressed", "Pressed"),
                    ("not_pressed", "Not Pressed"),
                    ("in_progress", "In Progress"),
                ],
                default="not_pressed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fanacallrequest",
            name="order_state",
            field=models.CharField(
                choices=[
                    ("pressed", "Pressed"),
                    ("not_pressed", "Not Pressed"),
                    ("in_progress", "In Progress"),
                ],
                default="not_pressed",
                max_length=20,
            ),
        ),
    ]
