# Generated by Django 5.0.7 on 2024-07-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fanaCallSetup", "0003_remove_fanacallrequest_handled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fanacallrequest",
            name="table_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
